---
# Source: monitor-micro-chart/templates/pondpulse-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pondpulse-service
spec:
  type: NodePort  
  selector:
    app: pondpulse
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
---
# Source: monitor-micro-chart/templates/dbribbit-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbribbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbribbit
  template:
    metadata:
      labels:
        app: dbribbit
    spec:
      containers:
        - name: dbribbit
          image: "tpaz1/dbribbit:latest"
          env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username 
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER    
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: database-url
---
# Source: monitor-micro-chart/templates/flytrap-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flytrap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flytrap
  template:
    metadata:
      labels:
        app: flytrap
    spec:
      containers:
        - name: flytrap
          image: "tpaz1/flytrap:latest"
---
# Source: monitor-micro-chart/templates/pondpulse-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pondpulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pondpulse
  template:
    metadata:
      labels:
        app: pondpulse
    spec:
      containers:
        - name: pondpulse
          image: "tpaz1/pondpulse:latest"
          ports:
            - containerPort: 5000
