version: '3.1'

services:
  mongo:
    image: mongo:6
    restart: always
    networks:
      - mynetwork
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    #      MONGO_INITDB_DATABASE: init

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_ui
    networks:
      - mynetwork
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  mynetwork:
    external:
      name: mynetwork