---
# Source: monitor-micro-chart/charts/app/templates/01-mongoDB-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: YWRtaW4=
---
# Source: monitor-micro-chart/charts/app/templates/04-mongoDB-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  database-url: mongodb-service
---
# Source: monitor-micro-chart/charts/app/templates/03-mongoDB-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
# Source: monitor-micro-chart/charts/app/templates/06-mongo-exp-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo-exp-service 
spec:
  selector:
    app: mongo-exp
  type: NodePort  
  ports:
    - protocol: TCP
      port:  8081 
      targetPort:  8081 
      nodePort:  30000
---
# Source: monitor-micro-chart/charts/microservices/templates/pondpulse-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pondpulse-service
spec:
  type: NodePort  
  selector:
    app: pondpulse
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
---
# Source: monitor-micro-chart/charts/app/templates/02-mongoDB-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username 
                  
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
---
# Source: monitor-micro-chart/charts/app/templates/05-mongo-exp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-exp
  labels:
    app: mongo-exp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-exp
  template:
    metadata:
      labels:
        app: mongo-exp
    spec:
      containers:
      - name: mongo-exp
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username 
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER    
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: database-url
---
# Source: monitor-micro-chart/charts/microservices/templates/dbribbit-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbribbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbribbit
  template:
    metadata:
      labels:
        app: dbribbit
    spec:
      initContainers:
        - name: init-sleep
          image: busybox   # lightweight image
          command: ["sleep", "60"]
      containers:
        - name: dbribbit
          image: "tpaz1/dbribbit:latest"
          env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username 
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER    
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: database-url
---
# Source: monitor-micro-chart/charts/microservices/templates/flytrap-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flytrap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flytrap
  template:
    metadata:
      labels:
        app: flytrap
    spec:
      initContainers:
        - name: init-sleep
          image: busybox   # lightweight image
          command: ["sleep", "60"]
      containers:
        - name: flytrap
          image: "tpaz1/flytrap:latest"
---
# Source: monitor-micro-chart/charts/microservices/templates/pondpulse-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pondpulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pondpulse
  template:
    metadata:
      labels:
        app: pondpulse
    spec:
      containers:
        - name: pondpulse
          image: "tpaz1/pondpulse:latest"
          ports:
            - containerPort: 5000
