apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-monitor-app
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: microservices-monitor-deployment
  project: default
  source:
    repoURL: https://github.com/tpaz1/Microservice-monitor.git
    path: ./deploy
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

