apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dbribbit.name }}
spec:
  replicas: {{ .Values.dbribbit.replicaCount }}
  selector:
    matchLabels:
      app: {{.Values.dbribbit.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.dbribbit.name }}
    spec:
      containers:
        - name: {{ .Values.dbribbit.name }}
          image: "{{ .Values.dbribbit.image.repository }}:{{ .Values.dbribbit.image.tag }}"
          env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username 
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
          - name: ME_CONFIG_MONGODB_SERVER    
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: database-url