apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pondpulse.service.name }}
spec:
  selector:
    app: {{ .Values.pondpulse.service.name }}
  ports:
    - port: {{ .Values.pondpulse.service.port }}
      targetPort: {{ .Values.pondpulse.service.targetPort }}